version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python3 manage.py test

      - run:
          name: code coverage
          command: |
            coverage run --source=trelloApp --omit=*/migrations/*,*/tests/*  manage.py test
            coverage html -d coverage

      - store_artifacts:
          path: coverage
          destination: coverage

  build_and_push_docker_container:
    machine: true
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t herrickz/trello-backend:$CIRCLE_BRANCH .
      - run: docker push herrickz/trello-backend:$CIRCLE_BRANCH

workflows:
  version: 2
  build_test_push_docker_container:
    jobs:
      - build_and_test
      - build_and_push_docker_container:
          requires:
            - build_and_test
          filters:
            branches:
              only: master