version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            python3 manage.py test

      - run:
          name: code coverage
          command: |
            coverage run --source=trelloApp --omit=*/migrations/*,*/tests/*  manage.py test
            coverage html -d coverage

      - store_artifacts:
          path: coverage
          destination: coverage