# Generated by Django 2.0.3 on 2018-12-04 03:01

from django.db import migrations, models
import trelloApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hashId',
            field=models.CharField(default=trelloApp.models._createHash, editable=False, max_length=10, unique=True),
        ),
    ]
