# Generated by Django 2.0.3 on 2018-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0003_auto_20181220_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
