# Generated by Django 2.0.3 on 2019-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0005_auto_20181221_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
